Use com.saucelabs as package name
aginteractive/Gradle-Sauce-Connect-Plugin pull request #4
Opened 2017-04-24 18:25 UTC by ndmanvar

2017-04-24 19:30 UTC, JohnRoach commented
Thank you Neil. Will be working with @tylerdave to find out why our build/test failed.

2017-04-24 22:02 UTC, johnroach requested changes

2017-04-24 22:02 UTC, JohnRoach commented on src/main/resources/META-INF/gradle-plugins/io.ndmanvar.SauceConnectPlugin.properties
> +implementation-class=com.saucelabs.SauceConnectPlugin
I think you need to change the file name here.

2017-04-24 22:02 UTC, JohnRoach commented on src/main/resources/META-INF/gradle-plugins/io.johnroach.SauceConnectPlugin.properties
> +implementation-class=com.saucelabs.SauceConnectPlugin
I believe this can be deleted.

2017-04-27 17:01 UTC, tylerdave commented
+1

2017-04-28 12:48 UTC, merged